import "./globals.css";
import Header from "@/components/Header";
import { UserProvider } from "@/context/UserContext";

export const metadata = {
    title: "MERN LOGIN REGISTER",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ja">
            <body>
                <UserProvider>
                    <Header />
                    <main>{children}</main>
                </UserProvider>
            </body>
        </html>
    );
}
